default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
    -   id: black
        args: # arguments to configure black
        -   --line-length=100
        -   --skip-string-normalization
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args:
        -   --max-line-length=100
        additional_dependencies:
        -   flake8-builtins==1.5.3
        -   flake8-bugbear==22.9.11
        -   flake8-comprehensions==3.2.3
        -   flake8-tidy-imports==4.1.0

